import React, { useContext, useState } from 'react'
import {CartMenu, DrawerMenu, Logo, Menu, Nav, SideMenuBars, SubMenu, CartItensValue} from './NavBarStyle'
import {CaretDown, MagnifyingGlass, User, ShoppingBagOpen, List} from 'phosphor-react';
import {ShopDrawerMenu, OurWorldDrawerMenu} from './ShopDrawerMenu';
import SideNavBar from './SideNavBar';
import Head from 'next/head';
import Link from 'next/link';
import { CartContext } from '../Context/CartContext';

const Navbar = () => {
    const [shopIsOpen, setShopIsOpen] = useState(false);
    const [ourWorldIsOpen, setOurWorldIsOpen] = useState(false);

    const [isOpen, setIsOpen] = useState(false);

  const {cart} = useContext(CartContext)

  return (
    <Nav>
        <Head>
        <title>Sayajeans | Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Menu>
            <SideMenuBars>
              
            <List size={20} color="gray" />
            </SideMenuBars>
            <DrawerMenu onClick={() => [setShopIsOpen(!shopIsOpen), setOurWorldIsOpen(false)]}>
                <span >Shop <CaretDown size={16} color="gray" /></span>
                {shopIsOpen && <ShopDrawerMenu/>}
            </DrawerMenu>
            <DrawerMenu onClick={() => [setOurWorldIsOpen(!ourWorldIsOpen), setShopIsOpen(false)]}>
                <span>Our World <CaretDown size={16} color="gray" /></span>
                {ourWorldIsOpen && <OurWorldDrawerMenu/>}
            </DrawerMenu>
        </Menu>
        
        <Link href="/">
        <Logo>
        SAYAJEANS
        </Logo>
        </Link>

        <Menu>
        <SubMenu>
        <MagnifyingGlass size={22} color="black" />
        </SubMenu>
        <SubMenu>
        <User size={22} color="black" />
        </SubMenu>
        <SubMenu>
        <CartMenu>
        <Link prefetch href="/Cart">
        <ShoppingBagOpen href='/Cart' size={22} color="black" />
        </Link>
       <CartItensValue>
        {cart.length}
        </CartItensValue> 
        
        </CartMenu>
        </SubMenu>
            </Menu>
    </Nav>
  )
}

export default Navbar;

