import React, { useContext, useEffect, useState } from 'react'
import {CartMenu, DrawerMenu, Logo, Menu, Nav, SideMenuBars, SubMenu, CartItensValue} from './NavBarStyle'
import {CaretDown, MagnifyingGlass, User, ShoppingBagOpen, List} from 'phosphor-react';
import {ShopDrawerMenu, OurWorldDrawerMenu} from './ShopDrawerMenu';
import SideNavBar from './SideNavBar';
import Head from 'next/head';
import Link from 'next/link';
import { CartContext } from '../Context/CartContext';
import Searchbar from './Login';
import Login from './Login';
import { AuthContext } from '../Context/AuthContext';

const Navbar = () => {
    const [shopIsOpen, setShopIsOpen] = useState(false);
    const [ourWorldIsOpen, setOurWorldIsOpen] = useState(false);
    const [LoginIsOpen, setLoginIsOpen] = useState(false);

    const {cart} = useContext(CartContext)
    const {user, Loged} = useContext(AuthContext)

    const [size, setSize] = useState<any>({
      width: undefined,
      height: undefined,
  });
  
  useEffect(() => {
    const handleResize = () => {
      setSize({
        width: window.innerWidth,
        height: window.innerHeight,
      })
    }
    window.addEventListener("resize", handleResize);
  
    return () => window.removeEventListener("resize", handleResize);
  }, []);
  
  useEffect(() => {
    if (size.width < 768 && {ourWorldIsOpen, shopIsOpen}) {
      setShopIsOpen(false)
      setOurWorldIsOpen(false)
    }
  }, [size.width, shopIsOpen, ourWorldIsOpen]);

  return (
    <Nav>
        <Head>
        <title>Sayajeans | Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Menu>
           <SideNavBar/>
            <DrawerMenu onClick={() => [setShopIsOpen(!shopIsOpen), setOurWorldIsOpen(false)]}>
                <span >Shop <CaretDown size={16} color="gray" /></span>
                {shopIsOpen && <ShopDrawerMenu/>}
            </DrawerMenu>
            <DrawerMenu onClick={() => [setOurWorldIsOpen(!ourWorldIsOpen), setShopIsOpen(false)]}>
                <span>Our World <CaretDown size={16} color="gray" /></span>
                {ourWorldIsOpen && <OurWorldDrawerMenu/>}
            </DrawerMenu>
        </Menu>
        
        <Link href="/">
        <Logo>
        SAYAJEANS
        </Logo>
        </Link>

        <Menu>
        <SubMenu onClick={() => setLoginIsOpen(!LoginIsOpen)}>
         <User size={22} color="black" />
       {LoginIsOpen && <Login/>}
        </SubMenu>
        <SubMenu>
        <CartMenu>
        <Link prefetch href="/Cart">
        <ShoppingBagOpen href='/Cart' size={22} color="black" />
        </Link>
       <CartItensValue>
        {cart.length}
        </CartItensValue> 
        
        </CartMenu>
        </SubMenu>
            </Menu>
    </Nav>
  )
}

export default Navbar;

function setOpen(arg0: boolean) {
  throw new Error('Function not implemented.');
}

